/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountModuleUsageItem {
    'metric': string;
    'moduleCode': string;
    'periodEnd': string;
    'periodStart': string;
    'value': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "metric",
            "baseName": "metric",
            "type": "string"
        },
        {
            "name": "moduleCode",
            "baseName": "moduleCode",
            "type": "string"
        },
        {
            "name": "periodEnd",
            "baseName": "periodEnd",
            "type": "string"
        },
        {
            "name": "periodStart",
            "baseName": "periodStart",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AccountModuleUsageItem.attributeTypeMap;
    }
}

