/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AccountModuleItem {
    /**
    * Auto-renewal flag
    */
    'autoRenew': boolean;
    /**
    * Expiration timestamp
    */
    'expiresAt'?: Date;
    /**
    * Module code
    */
    'moduleCode': string;
    /**
    * Module plan
    */
    'plan': string;
    /**
    * Module price in cents
    */
    'priceCents': number;
    /**
    * Activation timestamp
    */
    'startedAt'?: Date;
    /**
    * Module status
    */
    'status': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "autoRenew",
            "baseName": "autoRenew",
            "type": "boolean"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "moduleCode",
            "baseName": "moduleCode",
            "type": "string"
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "string"
        },
        {
            "name": "priceCents",
            "baseName": "priceCents",
            "type": "number"
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "Date"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AccountModuleItem.attributeTypeMap;
    }
}

