/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ApiTokenItem {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'active': boolean;
    'createdAt': Date;
    'expiresAt'?: Date;
    'id': number;
    'lastUsedAt'?: Date;
    'name': string;
    'profileIds'?: Array<string> | null;
    'revokedAt'?: Date;
    'scopes'?: Array<string> | null;
    'token'?: string;
    'truncatedToken'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "lastUsedAt",
            "baseName": "lastUsedAt",
            "type": "Date"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "profileIds",
            "baseName": "profileIds",
            "type": "Array<string>"
        },
        {
            "name": "revokedAt",
            "baseName": "revokedAt",
            "type": "Date"
        },
        {
            "name": "scopes",
            "baseName": "scopes",
            "type": "Array<string>"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "truncatedToken",
            "baseName": "truncatedToken",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ApiTokenItem.attributeTypeMap;
    }
}

