/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AuthTokenOutputBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    /**
    * JWT authentication token
    */
    'authenticationToken': string;
    /**
    * UTC timestamp when the token expires
    */
    'authenticationTokenExpiry': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "authenticationToken",
            "baseName": "authenticationToken",
            "type": "string"
        },
        {
            "name": "authenticationTokenExpiry",
            "baseName": "authenticationTokenExpiry",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return AuthTokenOutputBody.attributeTypeMap;
    }
}

