/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { BackupProfile } from './backupProfile';
import { BackupProfileAuth } from './backupProfileAuth';
import { BackupUser } from './backupUser';
import { BackupWebhook } from './backupWebhook';

export class BackupPayload {
    'exportedAt': Date;
    'profileAuth': Array<BackupProfileAuth> | null;
    'profiles': Array<BackupProfile> | null;
    'user': BackupUser;
    'version': number;
    'webhooks': Array<BackupWebhook> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "exportedAt",
            "baseName": "exportedAt",
            "type": "Date"
        },
        {
            "name": "profileAuth",
            "baseName": "profileAuth",
            "type": "Array<BackupProfileAuth>"
        },
        {
            "name": "profiles",
            "baseName": "profiles",
            "type": "Array<BackupProfile>"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "BackupUser"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        },
        {
            "name": "webhooks",
            "baseName": "webhooks",
            "type": "Array<BackupWebhook>"
        }    ];

    static getAttributeTypeMap() {
        return BackupPayload.attributeTypeMap;
    }
}

