/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BackupProfileAuth {
    'created': Date;
    'loginAvailable': boolean;
    'loginPayloadJson': string;
    'profileId': string;
    'profileJson': string;
    'qrExpiresAt': number;
    'qrLink': string;
    'qrPollingInterval': number;
    'qrTrackId': string;
    'qrTtl': number;
    'syncPayloadJson': string;
    'token': string;
    'updated': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "loginAvailable",
            "baseName": "loginAvailable",
            "type": "boolean"
        },
        {
            "name": "loginPayloadJson",
            "baseName": "loginPayloadJson",
            "type": "string"
        },
        {
            "name": "profileId",
            "baseName": "profileId",
            "type": "string"
        },
        {
            "name": "profileJson",
            "baseName": "profileJson",
            "type": "string"
        },
        {
            "name": "qrExpiresAt",
            "baseName": "qrExpiresAt",
            "type": "number"
        },
        {
            "name": "qrLink",
            "baseName": "qrLink",
            "type": "string"
        },
        {
            "name": "qrPollingInterval",
            "baseName": "qrPollingInterval",
            "type": "number"
        },
        {
            "name": "qrTrackId",
            "baseName": "qrTrackId",
            "type": "string"
        },
        {
            "name": "qrTtl",
            "baseName": "qrTtl",
            "type": "number"
        },
        {
            "name": "syncPayloadJson",
            "baseName": "syncPayloadJson",
            "type": "string"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return BackupProfileAuth.attributeTypeMap;
    }
}

