/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class BotTokenResponseBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'error'?: string;
    'hasSecret': boolean;
    'hasToken': boolean;
    'token'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        },
        {
            "name": "hasSecret",
            "baseName": "hasSecret",
            "type": "boolean"
        },
        {
            "name": "hasToken",
            "baseName": "hasToken",
            "type": "boolean"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BotTokenResponseBody.attributeTypeMap;
    }
}

