/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ChatHistoryInputBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'chatId': string;
    'cursor': string | null;
    'date': string | null;
    'limit': number | null;
    'markAll': boolean | null;
    'messageIds': Array<string> | null;
    'order': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "chatId",
            "baseName": "chatId",
            "type": "string"
        },
        {
            "name": "cursor",
            "baseName": "cursor",
            "type": "string"
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string"
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number"
        },
        {
            "name": "markAll",
            "baseName": "markAll",
            "type": "boolean"
        },
        {
            "name": "messageIds",
            "baseName": "messageIds",
            "type": "Array<string>"
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ChatHistoryInputBody.attributeTypeMap;
    }
}

