/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateApiTokenInputBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'expiresAt'?: string;
    'name': string;
    'profileIds'?: Array<string> | null;
    'scopes'?: Array<string> | null;
    'ttlDays'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "profileIds",
            "baseName": "profileIds",
            "type": "Array<string>"
        },
        {
            "name": "scopes",
            "baseName": "scopes",
            "type": "Array<string>"
        },
        {
            "name": "ttlDays",
            "baseName": "ttlDays",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CreateApiTokenInputBody.attributeTypeMap;
    }
}

