/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CreateProfileInputBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    /**
    * Integration type (max, maxbot, telegrambot, telegram, vk, whatsapp)
    */
    'integrationType': string;
    /**
    * Profile name (optional)
    */
    'name'?: string;
    /**
    * Plan tier (paid, free)
    */
    'planTier'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "integrationType",
            "baseName": "integrationType",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "planTier",
            "baseName": "planTier",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateProfileInputBody.attributeTypeMap;
    }
}

