/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DashboardMessagePoint } from './dashboardMessagePoint';

export class DashboardMessages30d {
    /**
    * UTC range start
    */
    'from': string;
    'points': Array<DashboardMessagePoint> | null;
    /**
    * UTC range end
    */
    'to': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "from",
            "baseName": "from",
            "type": "string"
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "Array<DashboardMessagePoint>"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DashboardMessages30d.attributeTypeMap;
    }
}

