/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DashboardKPI {
    /**
    * Account balance in cents
    */
    'balanceCents': number;
    /**
    * Profiles with active authorization
    */
    'profilesConnected': number;
    /**
    * Total profiles count
    */
    'profilesTotal': number;
    /**
    * Profiles with at least one quota configured
    */
    'profilesWithQuotas': number;
    /**
    * Profiles with at least one webhook
    */
    'profilesWithWebhooks': number;
    /**
    * Unread notifications count
    */
    'unreadNotifications': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "balanceCents",
            "baseName": "balanceCents",
            "type": "number"
        },
        {
            "name": "profilesConnected",
            "baseName": "profilesConnected",
            "type": "number"
        },
        {
            "name": "profilesTotal",
            "baseName": "profilesTotal",
            "type": "number"
        },
        {
            "name": "profilesWithQuotas",
            "baseName": "profilesWithQuotas",
            "type": "number"
        },
        {
            "name": "profilesWithWebhooks",
            "baseName": "profilesWithWebhooks",
            "type": "number"
        },
        {
            "name": "unreadNotifications",
            "baseName": "unreadNotifications",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DashboardKPI.attributeTypeMap;
    }
}

