/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DashboardSetup {
    'hasConnectedProfile': boolean;
    'hasOutgoingMessages': boolean;
    'hasProfiles': boolean;
    'hasQuota': boolean;
    'hasWebhook': boolean;
    /**
    * Next setup step code
    */
    'nextStep': string;
    /**
    * Progress in percent
    */
    'progressPercent': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "hasConnectedProfile",
            "baseName": "hasConnectedProfile",
            "type": "boolean"
        },
        {
            "name": "hasOutgoingMessages",
            "baseName": "hasOutgoingMessages",
            "type": "boolean"
        },
        {
            "name": "hasProfiles",
            "baseName": "hasProfiles",
            "type": "boolean"
        },
        {
            "name": "hasQuota",
            "baseName": "hasQuota",
            "type": "boolean"
        },
        {
            "name": "hasWebhook",
            "baseName": "hasWebhook",
            "type": "boolean"
        },
        {
            "name": "nextStep",
            "baseName": "nextStep",
            "type": "string"
        },
        {
            "name": "progressPercent",
            "baseName": "progressPercent",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DashboardSetup.attributeTypeMap;
    }
}

