/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DeleteMessageBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'chatId': string;
    'deleted': boolean;
    'forMe'?: boolean;
    'messageIds': Array<string> | null;
    'result'?: any | null;
    'seq'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "chatId",
            "baseName": "chatId",
            "type": "string"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "forMe",
            "baseName": "forMe",
            "type": "boolean"
        },
        {
            "name": "messageIds",
            "baseName": "messageIds",
            "type": "Array<string>"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "any"
        },
        {
            "name": "seq",
            "baseName": "seq",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DeleteMessageBody.attributeTypeMap;
    }
}

