/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InboxConversationItem {
    'chatId': string;
    'created': Date;
    'id': number;
    'integrationType': string;
    'lastMessageAt': Date;
    'lastMessageDirection': string;
    'lastMessageText': string;
    'profileId': string;
    'title': string;
    'unread': number;
    'updated': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "chatId",
            "baseName": "chatId",
            "type": "string"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "integrationType",
            "baseName": "integrationType",
            "type": "string"
        },
        {
            "name": "lastMessageAt",
            "baseName": "lastMessageAt",
            "type": "Date"
        },
        {
            "name": "lastMessageDirection",
            "baseName": "lastMessageDirection",
            "type": "string"
        },
        {
            "name": "lastMessageText",
            "baseName": "lastMessageText",
            "type": "string"
        },
        {
            "name": "profileId",
            "baseName": "profileId",
            "type": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "unread",
            "baseName": "unread",
            "type": "number"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return InboxConversationItem.attributeTypeMap;
    }
}

