/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MaxContactName } from './maxContactName';

export class MaxContact {
    'accountStatus'?: number;
    'baseRawUrl'?: string;
    'baseUrl'?: string;
    'country'?: string;
    'gender'?: number;
    'id'?: number;
    'link'?: string;
    'names'?: Array<MaxContactName> | null;
    'options'?: Array<string> | null;
    'phone'?: number;
    'photoId'?: number;
    'updateTime'?: number;
    'webApp'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accountStatus",
            "baseName": "accountStatus",
            "type": "number"
        },
        {
            "name": "baseRawUrl",
            "baseName": "baseRawUrl",
            "type": "string"
        },
        {
            "name": "baseUrl",
            "baseName": "baseUrl",
            "type": "string"
        },
        {
            "name": "country",
            "baseName": "country",
            "type": "string"
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "link",
            "baseName": "link",
            "type": "string"
        },
        {
            "name": "names",
            "baseName": "names",
            "type": "Array<MaxContactName>"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<string>"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "number"
        },
        {
            "name": "photoId",
            "baseName": "photoId",
            "type": "number"
        },
        {
            "name": "updateTime",
            "baseName": "updateTime",
            "type": "number"
        },
        {
            "name": "webApp",
            "baseName": "webApp",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MaxContact.attributeTypeMap;
    }
}

