/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MaxFolder {
    'elements'?: Array<{ [key: string]: any; }> | null;
    'filterSubjects'?: { [key: string]: Array<number> | null; };
    'filters'?: Array<number> | null;
    'id'?: string;
    'include'?: Array<number> | null;
    'options'?: Array<number> | null;
    'sourceId'?: number;
    'title'?: string;
    'updateTime'?: number;
    'widgets'?: Array<{ [key: string]: any; }> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "elements",
            "baseName": "elements",
            "type": "Array<{ [key: string]: any; }>"
        },
        {
            "name": "filterSubjects",
            "baseName": "filterSubjects",
            "type": "{ [key: string]: Array<number> | null; }"
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "Array<number>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "include",
            "baseName": "include",
            "type": "Array<number>"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<number>"
        },
        {
            "name": "sourceId",
            "baseName": "sourceId",
            "type": "number"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "updateTime",
            "baseName": "updateTime",
            "type": "number"
        },
        {
            "name": "widgets",
            "baseName": "widgets",
            "type": "Array<{ [key: string]: any; }>"
        }    ];

    static getAttributeTypeMap() {
        return MaxFolder.attributeTypeMap;
    }
}

