/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MaxFolder } from './maxFolder';

export class MaxFoldersResponseBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'folderSync'?: number;
    'folders'?: Array<MaxFolder> | null;
    'foldersOrder'?: Array<string> | null;
    'result'?: { [key: string]: any; };
    'seq': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "folderSync",
            "baseName": "folderSync",
            "type": "number"
        },
        {
            "name": "folders",
            "baseName": "folders",
            "type": "Array<MaxFolder>"
        },
        {
            "name": "foldersOrder",
            "baseName": "foldersOrder",
            "type": "Array<string>"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "seq",
            "baseName": "seq",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return MaxFoldersResponseBody.attributeTypeMap;
    }
}

