/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MaxContact } from './maxContact';

export class MaxProfile {
    'contact'?: MaxContact;
    'profileOptions'?: Array<any> | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "contact",
            "baseName": "contact",
            "type": "MaxContact"
        },
        {
            "name": "profileOptions",
            "baseName": "profileOptions",
            "type": "Array<any>"
        }    ];

    static getAttributeTypeMap() {
        return MaxProfile.attributeTypeMap;
    }
}

