/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MaxProfile } from './maxProfile';

export class MaxSetProfileResponseBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'profile'?: MaxProfile;
    'result'?: { [key: string]: any; };
    'seq': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "MaxProfile"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "seq",
            "baseName": "seq",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return MaxSetProfileResponseBody.attributeTypeMap;
    }
}

