/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MaxSetProfileInputBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'description'?: string;
    'firstName': string;
    'lastName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return MaxSetProfileInputBody.attributeTypeMap;
    }
}

