/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MaxUserSettingsPatch } from './maxUserSettingsPatch';

export class MaxSetUserSettingsInputBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    /**
    * MAX user settings patch
    */
    'user': MaxUserSettingsPatch;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "MaxUserSettingsPatch"
        }    ];

    static getAttributeTypeMap() {
        return MaxSetUserSettingsInputBody.attributeTypeMap;
    }
}

