/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MaxUserSettingsState } from './maxUserSettingsState';

export class MaxUserSettingsResponseBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'hash'?: string;
    'result'?: { [key: string]: any; };
    'seq': number;
    'user': MaxUserSettingsState;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "seq",
            "baseName": "seq",
            "type": "number"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "MaxUserSettingsState"
        }    ];

    static getAttributeTypeMap() {
        return MaxUserSettingsResponseBody.attributeTypeMap;
    }
}

