/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MaxUserSettingsState {
    'aLTKEYBOARD'?: boolean;
    'aUDIOTRANSCRIPTIONENABLED'?: boolean;
    'cHATSINVITE'?: string;
    'cHATSPUSHNOTIFICATION'?: string;
    'cHATSPUSHSOUND'?: string;
    'cONTENTLEVELACCESS'?: boolean;
    'dONTDISTURBUNTIL'?: number;
    'dOUBLETAPREACTIONDISABLED'?: boolean;
    'fAMILYPROTECTION'?: string;
    'hIDDEN'?: boolean;
    'iNACTIVETTL'?: string;
    'iNCOMINGCALL'?: string;
    'mCALLPUSHNOTIFICATION'?: string;
    'pUSHDETAILS'?: boolean;
    'pUSHNEWCONTACTS'?: boolean;
    'pUSHSOUND'?: string;
    'sAFEMODE'?: boolean;
    'sAFEMODENOPIN'?: boolean;
    'sEARCHBYPHONE'?: string;
    'sHOWREADMARK'?: boolean;
    'sTICKERSSUGGEST'?: string;
    'uNSAFEFILES'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "aLTKEYBOARD",
            "baseName": "ALT_KEYBOARD",
            "type": "boolean"
        },
        {
            "name": "aUDIOTRANSCRIPTIONENABLED",
            "baseName": "AUDIO_TRANSCRIPTION_ENABLED",
            "type": "boolean"
        },
        {
            "name": "cHATSINVITE",
            "baseName": "CHATS_INVITE",
            "type": "string"
        },
        {
            "name": "cHATSPUSHNOTIFICATION",
            "baseName": "CHATS_PUSH_NOTIFICATION",
            "type": "string"
        },
        {
            "name": "cHATSPUSHSOUND",
            "baseName": "CHATS_PUSH_SOUND",
            "type": "string"
        },
        {
            "name": "cONTENTLEVELACCESS",
            "baseName": "CONTENT_LEVEL_ACCESS",
            "type": "boolean"
        },
        {
            "name": "dONTDISTURBUNTIL",
            "baseName": "DONT_DISTURB_UNTIL",
            "type": "number"
        },
        {
            "name": "dOUBLETAPREACTIONDISABLED",
            "baseName": "DOUBLE_TAP_REACTION_DISABLED",
            "type": "boolean"
        },
        {
            "name": "fAMILYPROTECTION",
            "baseName": "FAMILY_PROTECTION",
            "type": "string"
        },
        {
            "name": "hIDDEN",
            "baseName": "HIDDEN",
            "type": "boolean"
        },
        {
            "name": "iNACTIVETTL",
            "baseName": "INACTIVE_TTL",
            "type": "string"
        },
        {
            "name": "iNCOMINGCALL",
            "baseName": "INCOMING_CALL",
            "type": "string"
        },
        {
            "name": "mCALLPUSHNOTIFICATION",
            "baseName": "M_CALL_PUSH_NOTIFICATION",
            "type": "string"
        },
        {
            "name": "pUSHDETAILS",
            "baseName": "PUSH_DETAILS",
            "type": "boolean"
        },
        {
            "name": "pUSHNEWCONTACTS",
            "baseName": "PUSH_NEW_CONTACTS",
            "type": "boolean"
        },
        {
            "name": "pUSHSOUND",
            "baseName": "PUSH_SOUND",
            "type": "string"
        },
        {
            "name": "sAFEMODE",
            "baseName": "SAFE_MODE",
            "type": "boolean"
        },
        {
            "name": "sAFEMODENOPIN",
            "baseName": "SAFE_MODE_NO_PIN",
            "type": "boolean"
        },
        {
            "name": "sEARCHBYPHONE",
            "baseName": "SEARCH_BY_PHONE",
            "type": "string"
        },
        {
            "name": "sHOWREADMARK",
            "baseName": "SHOW_READ_MARK",
            "type": "boolean"
        },
        {
            "name": "sTICKERSSUGGEST",
            "baseName": "STICKERS_SUGGEST",
            "type": "string"
        },
        {
            "name": "uNSAFEFILES",
            "baseName": "UNSAFE_FILES",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return MaxUserSettingsState.attributeTypeMap;
    }
}

