/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MaxVideoResolveInputBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'chatId'?: string;
    'messageId'?: string;
    'videoId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "chatId",
            "baseName": "chatId",
            "type": "string"
        },
        {
            "name": "messageId",
            "baseName": "messageId",
            "type": "string"
        },
        {
            "name": "videoId",
            "baseName": "videoId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return MaxVideoResolveInputBody.attributeTypeMap;
    }
}

