/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MaxWSCallResponseBody {
    'expectOpcode': number;
    'opcode': number;
    'result'?: any | null;
    'seq': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expectOpcode",
            "baseName": "expectOpcode",
            "type": "number"
        },
        {
            "name": "opcode",
            "baseName": "opcode",
            "type": "number"
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "any"
        },
        {
            "name": "seq",
            "baseName": "seq",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return MaxWSCallResponseBody.attributeTypeMap;
    }
}

