/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class MaxWSCallInputBody {
    /**
    * Expected response opcode. Defaults to opcode
    */
    'expectOpcode'?: number;
    /**
    * MAX websocket opcode to call
    */
    'opcode': number;
    'payload'?: any | null;
    /**
    * Request timeout in milliseconds (1000..30000)
    */
    'timeoutMs'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "expectOpcode",
            "baseName": "expectOpcode",
            "type": "number"
        },
        {
            "name": "opcode",
            "baseName": "opcode",
            "type": "number"
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "any"
        },
        {
            "name": "timeoutMs",
            "baseName": "timeoutMs",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return MaxWSCallInputBody.attributeTypeMap;
    }
}

