/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PollAuthorizationBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'expiresAt'?: number;
    'loginAvailable'?: boolean;
    'profile'?: any | null;
    'stateProfile': string;
    'token'?: string;
    'trackId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "number"
        },
        {
            "name": "loginAvailable",
            "baseName": "loginAvailable",
            "type": "boolean"
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "any"
        },
        {
            "name": "stateProfile",
            "baseName": "stateProfile",
            "type": "string"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        },
        {
            "name": "trackId",
            "baseName": "trackId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PollAuthorizationBody.attributeTypeMap;
    }
}

