/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProfileResponse {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    /**
    * Whether auto-renewal is enabled
    */
    'autoRenew': boolean;
    /**
    * Balance after transaction (only for create/renew)
    */
    'balanceAfter'?: number;
    /**
    * Creation time
    */
    'created': Date;
    /**
    * Device identifier
    */
    'deviceId': string;
    /**
    * Integration type
    */
    'integrationType': string;
    /**
    * Whether the profile is active
    */
    'isActive': boolean;
    /**
    * Whether the profile is authorized in the third-party service
    */
    'isAuthorized': boolean;
    /**
    * Profile name
    */
    'name': string;
    /**
    * Paid until time
    */
    'paidUntil': Date;
    /**
    * Plan tier (paid, free)
    */
    'planTier': string;
    /**
    * Renewal price in cents
    */
    'priceCents': number;
    /**
    * Unique profile identifier
    */
    'profileId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "autoRenew",
            "baseName": "autoRenew",
            "type": "boolean"
        },
        {
            "name": "balanceAfter",
            "baseName": "balanceAfter",
            "type": "number"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "deviceId",
            "baseName": "deviceId",
            "type": "string"
        },
        {
            "name": "integrationType",
            "baseName": "integrationType",
            "type": "string"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean"
        },
        {
            "name": "isAuthorized",
            "baseName": "isAuthorized",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "paidUntil",
            "baseName": "paidUntil",
            "type": "Date"
        },
        {
            "name": "planTier",
            "baseName": "planTier",
            "type": "string"
        },
        {
            "name": "priceCents",
            "baseName": "priceCents",
            "type": "number"
        },
        {
            "name": "profileId",
            "baseName": "profileId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProfileResponse.attributeTypeMap;
    }
}

