/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ProfileRenewOutputBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'autoRenew': boolean;
    'balanceAfter'?: number;
    'isActive': boolean;
    'paidUntil': Date;
    'priceCents': number;
    'profileId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "autoRenew",
            "baseName": "autoRenew",
            "type": "boolean"
        },
        {
            "name": "balanceAfter",
            "baseName": "balanceAfter",
            "type": "number"
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean"
        },
        {
            "name": "paidUntil",
            "baseName": "paidUntil",
            "type": "Date"
        },
        {
            "name": "priceCents",
            "baseName": "priceCents",
            "type": "number"
        },
        {
            "name": "profileId",
            "baseName": "profileId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProfileRenewOutputBody.attributeTypeMap;
    }
}

