/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ReadChatHumaInputBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'chatId': string;
    /**
    * Client mark timestamp in ms
    */
    'mark'?: number;
    'messageId': string;
    /**
    * READ_MESSAGE or SET_AS_UNREAD (aliases: read, unread)
    */
    'type'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "chatId",
            "baseName": "chatId",
            "type": "string"
        },
        {
            "name": "mark",
            "baseName": "mark",
            "type": "number"
        },
        {
            "name": "messageId",
            "baseName": "messageId",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReadChatHumaInputBody.attributeTypeMap;
    }
}

