/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RestoreDataInputBody {
    /**
    * Base64 encoded backup JSON
    */
    'backupData': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "backupData",
            "baseName": "backupData",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RestoreDataInputBody.attributeTypeMap;
    }
}

