/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SetSettingsInputBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'delaySendMessagesMilliseconds': number | null;
    'incomingWebhook': string | null;
    'markIncomingMessagesReaded': string | null;
    'markIncomingMessagesReadedOnReply': string | null;
    'outgoingAPIMessageWebhook': string | null;
    'outgoingMessageWebhook': string | null;
    'outgoingWebhook': string | null;
    'stateWebhook': string | null;
    'webhookUrl': string | null;
    'webhookUrlToken': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "delaySendMessagesMilliseconds",
            "baseName": "delaySendMessagesMilliseconds",
            "type": "number"
        },
        {
            "name": "incomingWebhook",
            "baseName": "incomingWebhook",
            "type": "string"
        },
        {
            "name": "markIncomingMessagesReaded",
            "baseName": "markIncomingMessagesReaded",
            "type": "string"
        },
        {
            "name": "markIncomingMessagesReadedOnReply",
            "baseName": "markIncomingMessagesReadedOnReply",
            "type": "string"
        },
        {
            "name": "outgoingAPIMessageWebhook",
            "baseName": "outgoingAPIMessageWebhook",
            "type": "string"
        },
        {
            "name": "outgoingMessageWebhook",
            "baseName": "outgoingMessageWebhook",
            "type": "string"
        },
        {
            "name": "outgoingWebhook",
            "baseName": "outgoingWebhook",
            "type": "string"
        },
        {
            "name": "stateWebhook",
            "baseName": "stateWebhook",
            "type": "string"
        },
        {
            "name": "webhookUrl",
            "baseName": "webhookUrl",
            "type": "string"
        },
        {
            "name": "webhookUrlToken",
            "baseName": "webhookUrlToken",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SetSettingsInputBody.attributeTypeMap;
    }
}

