/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TelegramPhoneVerifyConfirmResponseBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'verified': boolean;
    'verifiedPhoneE164': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "verified",
            "baseName": "verified",
            "type": "boolean"
        },
        {
            "name": "verifiedPhoneE164",
            "baseName": "verifiedPhoneE164",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TelegramPhoneVerifyConfirmResponseBody.attributeTypeMap;
    }
}

