/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TopUpStatusResponseItem {
    'amountCents': number;
    'confirmedAt'?: Date;
    'createdAt': Date;
    'currency': string;
    'errorMessage'?: string;
    'expiresAt'?: Date;
    'paymentUrl'?: string;
    'provider': string;
    'providerPaymentId': string;
    'status': string;
    'topupId': string;
    'updatedAt': Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amountCents",
            "baseName": "amountCents",
            "type": "number"
        },
        {
            "name": "confirmedAt",
            "baseName": "confirmedAt",
            "type": "Date"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "paymentUrl",
            "baseName": "paymentUrl",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "string"
        },
        {
            "name": "providerPaymentId",
            "baseName": "providerPaymentId",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "topupId",
            "baseName": "topupId",
            "type": "string"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return TopUpStatusResponseItem.attributeTypeMap;
    }
}

