/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TopUpResponseBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    /**
    * Amount topped up
    */
    'amountCents': number;
    /**
    * Currency code
    */
    'currency': string;
    /**
    * Top-up expiration time
    */
    'expiresAt'?: Date;
    /**
    * Hosted checkout URL
    */
    'paymentUrl'?: string;
    /**
    * Top-up status
    */
    'status': string;
    /**
    * Top-up identifier
    */
    'topupId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "amountCents",
            "baseName": "amountCents",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string"
        },
        {
            "name": "expiresAt",
            "baseName": "expiresAt",
            "type": "Date"
        },
        {
            "name": "paymentUrl",
            "baseName": "paymentUrl",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "topupId",
            "baseName": "topupId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return TopUpResponseBody.attributeTypeMap;
    }
}

