/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UpdateAccountModuleInputBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    /**
    * Enable or disable auto-renewal
    */
    'autoRenew'?: boolean;
    /**
    * Whether module should be enabled
    */
    'enabled': boolean;
    /**
    * Plan (monthly, annual, trial)
    */
    'plan'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "autoRenew",
            "baseName": "autoRenew",
            "type": "boolean"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean"
        },
        {
            "name": "plan",
            "baseName": "plan",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UpdateAccountModuleInputBody.attributeTypeMap;
    }
}

