/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AccountModuleItem } from './accountModuleItem';

export class UpdateAccountModuleResponseBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'item': AccountModuleItem;
    'updated': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "AccountModuleItem"
        },
        {
            "name": "updated",
            "baseName": "updated",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return UpdateAccountModuleResponseBody.attributeTypeMap;
    }
}

