/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UserMeResponseBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    /**
    * Баланс в копейках
    */
    'balance': number;
    /**
    * Время создания аккаунта
    */
    'created': Date;
    /**
    * Email пользователя
    */
    'email': string;
    /**
    * Время подтверждения email
    */
    'emailVerifiedAt'?: Date;
    /**
    * Можно ли создавать бесплатные профили
    */
    'freeProfileEligible': boolean;
    /**
    * Лимит бесплатных профилей на аккаунт
    */
    'maxFreeProfilesPerAccount': number;
    /**
    * Время подтверждения телефона
    */
    'phoneVerifiedAt'?: Date;
    /**
    * Статус Telegram-верификации телефона
    */
    'telegramVerificationStatus': string;
    /**
    * ID пользователя
    */
    'userId': number;
    /**
    * Подтвержденный телефон в формате E.164
    */
    'verifiedPhoneE164'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "emailVerifiedAt",
            "baseName": "emailVerifiedAt",
            "type": "Date"
        },
        {
            "name": "freeProfileEligible",
            "baseName": "freeProfileEligible",
            "type": "boolean"
        },
        {
            "name": "maxFreeProfilesPerAccount",
            "baseName": "maxFreeProfilesPerAccount",
            "type": "number"
        },
        {
            "name": "phoneVerifiedAt",
            "baseName": "phoneVerifiedAt",
            "type": "Date"
        },
        {
            "name": "telegramVerificationStatus",
            "baseName": "telegramVerificationStatus",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number"
        },
        {
            "name": "verifiedPhoneE164",
            "baseName": "verifiedPhoneE164",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserMeResponseBody.attributeTypeMap;
    }
}

