/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UserInboxConversationMeta {
    'archived': boolean;
    'avatarUrl'?: string;
    'muted': boolean;
    'starred': boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean"
        },
        {
            "name": "avatarUrl",
            "baseName": "avatarUrl",
            "type": "string"
        },
        {
            "name": "muted",
            "baseName": "muted",
            "type": "boolean"
        },
        {
            "name": "starred",
            "baseName": "starred",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return UserInboxConversationMeta.attributeTypeMap;
    }
}

