/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UserInboxMessageItem {
    'autoResponder'?: any | null;
    'chatId': string;
    'clientId'?: string;
    'conversationId': number;
    'created': Date;
    'direction': string;
    'id': number;
    'integrationType': string;
    'media'?: any | null;
    'messageId': string;
    'profileId': string;
    'readAt'?: Date;
    'status': string;
    'text': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "autoResponder",
            "baseName": "autoResponder",
            "type": "any"
        },
        {
            "name": "chatId",
            "baseName": "chatId",
            "type": "string"
        },
        {
            "name": "clientId",
            "baseName": "clientId",
            "type": "string"
        },
        {
            "name": "conversationId",
            "baseName": "conversationId",
            "type": "number"
        },
        {
            "name": "created",
            "baseName": "created",
            "type": "Date"
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "integrationType",
            "baseName": "integrationType",
            "type": "string"
        },
        {
            "name": "media",
            "baseName": "media",
            "type": "any"
        },
        {
            "name": "messageId",
            "baseName": "messageId",
            "type": "string"
        },
        {
            "name": "profileId",
            "baseName": "profileId",
            "type": "string"
        },
        {
            "name": "readAt",
            "baseName": "readAt",
            "type": "Date"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserInboxMessageItem.attributeTypeMap;
    }
}

