/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UserInboxConversationActionInputBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'action': UserInboxConversationActionInputBody.ActionEnum;
    'conversationId': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "UserInboxConversationActionInputBody.ActionEnum"
        },
        {
            "name": "conversationId",
            "baseName": "conversationId",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UserInboxConversationActionInputBody.attributeTypeMap;
    }
}

export namespace UserInboxConversationActionInputBody {
    export enum ActionEnum {
        Mute = <any> 'mute',
        Archive = <any> 'archive',
        Star = <any> 'star'
    }
}
