/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserInboxAvailableProfile } from './userInboxAvailableProfile';
import { UserInboxConversationMeta } from './userInboxConversationMeta';

export class UserInboxConversationItem {
    'availableProfiles': Array<UserInboxAvailableProfile> | null;
    'chatId': string;
    'conversationId': number;
    'integrationType': string;
    'lastMessageAt'?: Date;
    'lastMessageDirection': string;
    'lastMessageText': string;
    'lastSenderProfileId'?: string;
    'meta': UserInboxConversationMeta;
    'title': string;
    'unread': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "availableProfiles",
            "baseName": "availableProfiles",
            "type": "Array<UserInboxAvailableProfile>"
        },
        {
            "name": "chatId",
            "baseName": "chatId",
            "type": "string"
        },
        {
            "name": "conversationId",
            "baseName": "conversationId",
            "type": "number"
        },
        {
            "name": "integrationType",
            "baseName": "integrationType",
            "type": "string"
        },
        {
            "name": "lastMessageAt",
            "baseName": "lastMessageAt",
            "type": "Date"
        },
        {
            "name": "lastMessageDirection",
            "baseName": "lastMessageDirection",
            "type": "string"
        },
        {
            "name": "lastMessageText",
            "baseName": "lastMessageText",
            "type": "string"
        },
        {
            "name": "lastSenderProfileId",
            "baseName": "lastSenderProfileId",
            "type": "string"
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "UserInboxConversationMeta"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "unread",
            "baseName": "unread",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return UserInboxConversationItem.attributeTypeMap;
    }
}

