/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DashboardKPI } from './dashboardKPI';
import { DashboardMessages30d } from './dashboardMessages30d';
import { DashboardSetup } from './dashboardSetup';

export class UserDashboardSummaryResponseBody {
    /**
    * A URL to the JSON Schema for this object.
    */
    '$schema'?: string;
    'kpi': DashboardKPI;
    'messages30d': DashboardMessages30d;
    'setup': DashboardSetup;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "$schema",
            "baseName": "$schema",
            "type": "string"
        },
        {
            "name": "kpi",
            "baseName": "kpi",
            "type": "DashboardKPI"
        },
        {
            "name": "messages30d",
            "baseName": "messages30d",
            "type": "DashboardMessages30d"
        },
        {
            "name": "setup",
            "baseName": "setup",
            "type": "DashboardSetup"
        }    ];

    static getAttributeTypeMap() {
        return UserDashboardSummaryResponseBody.attributeTypeMap;
    }
}

