/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { ErrorModel } from '../model/errorModel';
import { MaxChatSubscriptionInputBody } from '../model/maxChatSubscriptionInputBody';
import { MaxChatSubscriptionResponseBody } from '../model/maxChatSubscriptionResponseBody';
import { MaxChatsByIDsInputBody } from '../model/maxChatsByIDsInputBody';
import { MaxChatsByIDsResponseBody } from '../model/maxChatsByIDsResponseBody';
import { MaxCreateFolderInputBody } from '../model/maxCreateFolderInputBody';
import { MaxFoldersResponseBody } from '../model/maxFoldersResponseBody';
import { MaxReorderFoldersInputBody } from '../model/maxReorderFoldersInputBody';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://api.relaya.ru/v1';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum ChatsApiApiKeys {
    ApiKeyAuth,
}

export class ChatsApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'ApiKeyAuth': new ApiKeyAuth('header', 'X-Profile-Token'),
        'BearerAuth': new HttpBearerAuth(),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: ChatsApiApiKeys, value: string) {
        (this.authentications as any)[ChatsApiApiKeys[key]].apiKey = value;
    }

    set accessToken(accessToken: string | (() => string)) {
        this.authentications.BearerAuth.accessToken = accessToken;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * 
     * @summary Delete MAX folder
     * @param profileId Profile ID
     * @param integration Integration type
     * @param folderId Folder ID
     */
    public async deleteProfilesProfileIdIntegrationsIntegrationFoldersFolderId (profileId: string, integration: string, folderId: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: MaxFoldersResponseBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/folders/{folderId}'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)))
            .replace('{' + 'folderId' + '}', encodeURIComponent(String(folderId)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling deleteProfilesProfileIdIntegrationsIntegrationFoldersFolderId.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling deleteProfilesProfileIdIntegrationsIntegrationFoldersFolderId.');
        }

        // verify required parameter 'folderId' is not null or undefined
        if (folderId === null || folderId === undefined) {
            throw new Error('Required parameter folderId was null or undefined when calling deleteProfilesProfileIdIntegrationsIntegrationFoldersFolderId.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'DELETE',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MaxFoldersResponseBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "MaxFoldersResponseBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary List MAX folders
     * @param profileId Profile ID
     * @param integration Integration type
     * @param folderSync Folder sync cursor (default 0)
     */
    public async getProfilesProfileIdIntegrationsIntegrationFolders (profileId: string, integration: string, folderSync?: number, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: MaxFoldersResponseBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/folders'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling getProfilesProfileIdIntegrationsIntegrationFolders.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling getProfilesProfileIdIntegrationsIntegrationFolders.');
        }

        if (folderSync !== undefined) {
            localVarQueryParameters['folderSync'] = ObjectSerializer.serialize(folderSync, "number");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'GET',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MaxFoldersResponseBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "MaxFoldersResponseBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Get chats by IDs
     * @param profileId Profile ID
     * @param integration Integration type
     * @param maxChatsByIDsInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationChatsByIds (profileId: string, integration: string, maxChatsByIDsInputBody: MaxChatsByIDsInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: MaxChatsByIDsResponseBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/chats/by-ids'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationChatsByIds.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationChatsByIds.');
        }

        // verify required parameter 'maxChatsByIDsInputBody' is not null or undefined
        if (maxChatsByIDsInputBody === null || maxChatsByIDsInputBody === undefined) {
            throw new Error('Required parameter maxChatsByIDsInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationChatsByIds.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(maxChatsByIDsInputBody, "MaxChatsByIDsInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MaxChatsByIDsResponseBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "MaxChatsByIDsResponseBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Subscribe/unsubscribe chat updates
     * @param profileId Profile ID
     * @param integration Integration type
     * @param maxChatSubscriptionInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationChatsSubscription (profileId: string, integration: string, maxChatSubscriptionInputBody: MaxChatSubscriptionInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: MaxChatSubscriptionResponseBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/chats/subscription'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationChatsSubscription.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationChatsSubscription.');
        }

        // verify required parameter 'maxChatSubscriptionInputBody' is not null or undefined
        if (maxChatSubscriptionInputBody === null || maxChatSubscriptionInputBody === undefined) {
            throw new Error('Required parameter maxChatSubscriptionInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationChatsSubscription.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(maxChatSubscriptionInputBody, "MaxChatSubscriptionInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MaxChatSubscriptionResponseBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "MaxChatSubscriptionResponseBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Create MAX folder
     * @param profileId Profile ID
     * @param integration Integration type
     * @param maxCreateFolderInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationFolders (profileId: string, integration: string, maxCreateFolderInputBody: MaxCreateFolderInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: MaxFoldersResponseBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/folders'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationFolders.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationFolders.');
        }

        // verify required parameter 'maxCreateFolderInputBody' is not null or undefined
        if (maxCreateFolderInputBody === null || maxCreateFolderInputBody === undefined) {
            throw new Error('Required parameter maxCreateFolderInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationFolders.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(maxCreateFolderInputBody, "MaxCreateFolderInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MaxFoldersResponseBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "MaxFoldersResponseBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Reorder MAX folders
     * @param profileId Profile ID
     * @param integration Integration type
     * @param maxReorderFoldersInputBody 
     */
    public async putProfilesProfileIdIntegrationsIntegrationFoldersOrder (profileId: string, integration: string, maxReorderFoldersInputBody: MaxReorderFoldersInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: MaxFoldersResponseBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/folders/order'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling putProfilesProfileIdIntegrationsIntegrationFoldersOrder.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling putProfilesProfileIdIntegrationsIntegrationFoldersOrder.');
        }

        // verify required parameter 'maxReorderFoldersInputBody' is not null or undefined
        if (maxReorderFoldersInputBody === null || maxReorderFoldersInputBody === undefined) {
            throw new Error('Required parameter maxReorderFoldersInputBody was null or undefined when calling putProfilesProfileIdIntegrationsIntegrationFoldersOrder.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'PUT',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(maxReorderFoldersInputBody, "MaxReorderFoldersInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MaxFoldersResponseBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "MaxFoldersResponseBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
