/**
 * Relaya
 * API for Relaya integrations and management
 *
 * The version of the OpenAPI document: (devel)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import localVarRequest from 'request';
import http from 'http';

/* tslint:disable:no-unused-locals */
import { ChatHistoryInputBody } from '../model/chatHistoryInputBody';
import { DeleteMessageBody } from '../model/deleteMessageBody';
import { DeleteMessageInputBody } from '../model/deleteMessageInputBody';
import { EditMessageInputBody } from '../model/editMessageInputBody';
import { ErrorModel } from '../model/errorModel';
import { ForwardMessageInputBody } from '../model/forwardMessageInputBody';
import { MaxVideoResolveInputBody } from '../model/maxVideoResolveInputBody';
import { MaxVideoResolveResponseBody } from '../model/maxVideoResolveResponseBody';
import { MessageResponseBody } from '../model/messageResponseBody';
import { ReadChatBody } from '../model/readChatBody';
import { ReadChatHumaInputBody } from '../model/readChatHumaInputBody';
import { RemoveReactionBody } from '../model/removeReactionBody';
import { RemoveReactionHumaInputBody } from '../model/removeReactionHumaInputBody';
import { SendMessageInputBody } from '../model/sendMessageInputBody';
import { SendReactionBody } from '../model/sendReactionBody';
import { SendReactionHumaInputBody } from '../model/sendReactionHumaInputBody';
import { SendReplyMessageInputBody } from '../model/sendReplyMessageInputBody';
import { SendTypingInputBody } from '../model/sendTypingInputBody';
import { SendTypingResponseBody } from '../model/sendTypingResponseBody';

import { ObjectSerializer, Authentication, VoidAuth, Interceptor } from '../model/models';
import { HttpBasicAuth, HttpBearerAuth, ApiKeyAuth, OAuth } from '../model/models';

import { HttpError, RequestFile } from './apis';

let defaultBasePath = 'https://api.relaya.ru/v1';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum MessagesApiApiKeys {
    ApiKeyAuth,
}

export class MessagesApi {
    protected _basePath = defaultBasePath;
    protected _defaultHeaders : any = {};
    protected _useQuerystring : boolean = false;

    protected authentications = {
        'default': <Authentication>new VoidAuth(),
        'ApiKeyAuth': new ApiKeyAuth('header', 'X-Profile-Token'),
        'BearerAuth': new HttpBearerAuth(),
    }

    protected interceptors: Interceptor[] = [];

    constructor(basePath?: string);
    constructor(basePathOrUsername: string, password?: string, basePath?: string) {
        if (password) {
            if (basePath) {
                this.basePath = basePath;
            }
        } else {
            if (basePathOrUsername) {
                this.basePath = basePathOrUsername
            }
        }
    }

    set useQuerystring(value: boolean) {
        this._useQuerystring = value;
    }

    set basePath(basePath: string) {
        this._basePath = basePath;
    }

    set defaultHeaders(defaultHeaders: any) {
        this._defaultHeaders = defaultHeaders;
    }

    get defaultHeaders() {
        return this._defaultHeaders;
    }

    get basePath() {
        return this._basePath;
    }

    public setDefaultAuthentication(auth: Authentication) {
        this.authentications.default = auth;
    }

    public setApiKey(key: MessagesApiApiKeys, value: string) {
        (this.authentications as any)[MessagesApiApiKeys[key]].apiKey = value;
    }

    set accessToken(accessToken: string | (() => string)) {
        this.authentications.BearerAuth.accessToken = accessToken;
    }

    public addInterceptor(interceptor: Interceptor) {
        this.interceptors.push(interceptor);
    }

    /**
     * 
     * @summary Remove reaction
     * @param profileId Profile ID
     * @param integration Integration type
     * @param removeReactionHumaInputBody 
     */
    public async deleteProfilesProfileIdIntegrationsIntegrationMessagesReactions (profileId: string, integration: string, removeReactionHumaInputBody: RemoveReactionHumaInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: RemoveReactionBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/messages/reactions'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling deleteProfilesProfileIdIntegrationsIntegrationMessagesReactions.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling deleteProfilesProfileIdIntegrationsIntegrationMessagesReactions.');
        }

        // verify required parameter 'removeReactionHumaInputBody' is not null or undefined
        if (removeReactionHumaInputBody === null || removeReactionHumaInputBody === undefined) {
            throw new Error('Required parameter removeReactionHumaInputBody was null or undefined when calling deleteProfilesProfileIdIntegrationsIntegrationMessagesReactions.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'DELETE',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(removeReactionHumaInputBody, "RemoveReactionHumaInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: RemoveReactionBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "RemoveReactionBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Send message
     * @param profileId Profile ID
     * @param integration Integration type
     * @param sendMessageInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationMessages (profileId: string, integration: string, sendMessageInputBody: SendMessageInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: MessageResponseBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/messages'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessages.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessages.');
        }

        // verify required parameter 'sendMessageInputBody' is not null or undefined
        if (sendMessageInputBody === null || sendMessageInputBody === undefined) {
            throw new Error('Required parameter sendMessageInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessages.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(sendMessageInputBody, "SendMessageInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MessageResponseBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "MessageResponseBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Delete message
     * @param profileId Profile ID
     * @param integration Integration type
     * @param deleteMessageInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationMessagesDelete (profileId: string, integration: string, deleteMessageInputBody: DeleteMessageInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: DeleteMessageBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/messages/delete'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesDelete.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesDelete.');
        }

        // verify required parameter 'deleteMessageInputBody' is not null or undefined
        if (deleteMessageInputBody === null || deleteMessageInputBody === undefined) {
            throw new Error('Required parameter deleteMessageInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesDelete.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(deleteMessageInputBody, "DeleteMessageInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: DeleteMessageBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "DeleteMessageBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Edit message
     * @param profileId Profile ID
     * @param integration Integration type
     * @param editMessageInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationMessagesEdit (profileId: string, integration: string, editMessageInputBody: EditMessageInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: MessageResponseBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/messages/edit'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesEdit.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesEdit.');
        }

        // verify required parameter 'editMessageInputBody' is not null or undefined
        if (editMessageInputBody === null || editMessageInputBody === undefined) {
            throw new Error('Required parameter editMessageInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesEdit.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(editMessageInputBody, "EditMessageInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MessageResponseBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "MessageResponseBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Forward message
     * @param profileId Profile ID
     * @param integration Integration type
     * @param forwardMessageInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationMessagesForward (profileId: string, integration: string, forwardMessageInputBody: ForwardMessageInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: MessageResponseBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/messages/forward'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesForward.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesForward.');
        }

        // verify required parameter 'forwardMessageInputBody' is not null or undefined
        if (forwardMessageInputBody === null || forwardMessageInputBody === undefined) {
            throw new Error('Required parameter forwardMessageInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesForward.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(forwardMessageInputBody, "ForwardMessageInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MessageResponseBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "MessageResponseBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Get chat history
     * @param profileId Profile ID
     * @param integration Integration type
     * @param chatHistoryInputBody 
     * @param limit 
     * @param cursor 
     * @param date 
     * @param order 
     * @param markAll 
     * @param messageIds 
     */
    public async postProfilesProfileIdIntegrationsIntegrationMessagesHistory (profileId: string, integration: string, chatHistoryInputBody: ChatHistoryInputBody, limit?: number, cursor?: string, date?: string, order?: string, markAll?: boolean, messageIds?: string, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: any;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/messages/history'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesHistory.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesHistory.');
        }

        // verify required parameter 'chatHistoryInputBody' is not null or undefined
        if (chatHistoryInputBody === null || chatHistoryInputBody === undefined) {
            throw new Error('Required parameter chatHistoryInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesHistory.');
        }

        if (limit !== undefined) {
            localVarQueryParameters['limit'] = ObjectSerializer.serialize(limit, "number");
        }

        if (cursor !== undefined) {
            localVarQueryParameters['cursor'] = ObjectSerializer.serialize(cursor, "string");
        }

        if (date !== undefined) {
            localVarQueryParameters['date'] = ObjectSerializer.serialize(date, "string");
        }

        if (order !== undefined) {
            localVarQueryParameters['order'] = ObjectSerializer.serialize(order, "string");
        }

        if (markAll !== undefined) {
            localVarQueryParameters['markAll'] = ObjectSerializer.serialize(markAll, "boolean");
        }

        if (messageIds !== undefined) {
            localVarQueryParameters['messageIds'] = ObjectSerializer.serialize(messageIds, "string");
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(chatHistoryInputBody, "ChatHistoryInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "any");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Send reaction
     * @param profileId Profile ID
     * @param integration Integration type
     * @param sendReactionHumaInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationMessagesReactions (profileId: string, integration: string, sendReactionHumaInputBody: SendReactionHumaInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: SendReactionBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/messages/reactions'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesReactions.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesReactions.');
        }

        // verify required parameter 'sendReactionHumaInputBody' is not null or undefined
        if (sendReactionHumaInputBody === null || sendReactionHumaInputBody === undefined) {
            throw new Error('Required parameter sendReactionHumaInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesReactions.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(sendReactionHumaInputBody, "SendReactionHumaInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: SendReactionBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "SendReactionBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Mark chat read
     * @param profileId Profile ID
     * @param integration Integration type
     * @param readChatHumaInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationMessagesRead (profileId: string, integration: string, readChatHumaInputBody: ReadChatHumaInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: ReadChatBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/messages/read'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesRead.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesRead.');
        }

        // verify required parameter 'readChatHumaInputBody' is not null or undefined
        if (readChatHumaInputBody === null || readChatHumaInputBody === undefined) {
            throw new Error('Required parameter readChatHumaInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesRead.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(readChatHumaInputBody, "ReadChatHumaInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: ReadChatBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "ReadChatBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Reply message
     * @param profileId Profile ID
     * @param integration Integration type
     * @param sendReplyMessageInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationMessagesReply (profileId: string, integration: string, sendReplyMessageInputBody: SendReplyMessageInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: MessageResponseBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/messages/reply'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesReply.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesReply.');
        }

        // verify required parameter 'sendReplyMessageInputBody' is not null or undefined
        if (sendReplyMessageInputBody === null || sendReplyMessageInputBody === undefined) {
            throw new Error('Required parameter sendReplyMessageInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesReply.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(sendReplyMessageInputBody, "SendReplyMessageInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MessageResponseBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "MessageResponseBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Send typing status
     * @param profileId Profile ID
     * @param integration Integration type
     * @param sendTypingInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationMessagesTyping (profileId: string, integration: string, sendTypingInputBody: SendTypingInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: SendTypingResponseBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/messages/typing'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesTyping.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesTyping.');
        }

        // verify required parameter 'sendTypingInputBody' is not null or undefined
        if (sendTypingInputBody === null || sendTypingInputBody === undefined) {
            throw new Error('Required parameter sendTypingInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesTyping.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(sendTypingInputBody, "SendTypingInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: SendTypingResponseBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "SendTypingResponseBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Mark chat as unread
     * @param profileId Profile ID
     * @param integration Integration type
     * @param readChatHumaInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationMessagesUnread (profileId: string, integration: string, readChatHumaInputBody: ReadChatHumaInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: ReadChatBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/messages/unread'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesUnread.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesUnread.');
        }

        // verify required parameter 'readChatHumaInputBody' is not null or undefined
        if (readChatHumaInputBody === null || readChatHumaInputBody === undefined) {
            throw new Error('Required parameter readChatHumaInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationMessagesUnread.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(readChatHumaInputBody, "ReadChatHumaInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: ReadChatBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "ReadChatBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Resolve video links by video ID
     * @param profileId Profile ID
     * @param integration Integration type
     * @param maxVideoResolveInputBody 
     */
    public async postProfilesProfileIdIntegrationsIntegrationVideosResolve (profileId: string, integration: string, maxVideoResolveInputBody: MaxVideoResolveInputBody, options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body: MaxVideoResolveResponseBody;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/videos/resolve'
            .replace('{' + 'profileId' + '}', encodeURIComponent(String(profileId)))
            .replace('{' + 'integration' + '}', encodeURIComponent(String(integration)));
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        const produces = ['application/json', 'application/problem+json'];
        // give precedence to 'application/json'
        if (produces.indexOf('application/json') >= 0) {
            localVarHeaderParams.Accept = 'application/json';
        } else {
            localVarHeaderParams.Accept = produces.join(',');
        }
        let localVarFormParams: any = {};

        // verify required parameter 'profileId' is not null or undefined
        if (profileId === null || profileId === undefined) {
            throw new Error('Required parameter profileId was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationVideosResolve.');
        }

        // verify required parameter 'integration' is not null or undefined
        if (integration === null || integration === undefined) {
            throw new Error('Required parameter integration was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationVideosResolve.');
        }

        // verify required parameter 'maxVideoResolveInputBody' is not null or undefined
        if (maxVideoResolveInputBody === null || maxVideoResolveInputBody === undefined) {
            throw new Error('Required parameter maxVideoResolveInputBody was null or undefined when calling postProfilesProfileIdIntegrationsIntegrationVideosResolve.');
        }

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
            body: ObjectSerializer.serialize(maxVideoResolveInputBody, "MaxVideoResolveInputBody")
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body: MaxVideoResolveResponseBody;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            body = ObjectSerializer.deserialize(body, "MaxVideoResolveResponseBody");
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
    /**
     * 
     * @summary Upload file
     */
    public async profilesProfileIdIntegrationsIntegrationMessagesFilesPost (options: {headers: {[name: string]: string}} = {headers: {}}) : Promise<{ response: http.IncomingMessage; body?: any;  }> {
        const localVarPath = this.basePath + '/profiles/{profileId}/integrations/{integration}/messages/files';
        let localVarQueryParameters: any = {};
        let localVarHeaderParams: any = (<any>Object).assign({}, this._defaultHeaders);
        let localVarFormParams: any = {};

        (<any>Object).assign(localVarHeaderParams, options.headers);

        let localVarUseFormData = false;

        let localVarRequestOptions: localVarRequest.Options = {
            method: 'POST',
            qs: localVarQueryParameters,
            headers: localVarHeaderParams,
            uri: localVarPath,
            useQuerystring: this._useQuerystring,
            json: true,
        };

        let authenticationPromise = Promise.resolve();
        if (this.authentications.ApiKeyAuth.apiKey) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.ApiKeyAuth.applyToRequest(localVarRequestOptions));
        }
        if (this.authentications.BearerAuth.accessToken) {
            authenticationPromise = authenticationPromise.then(() => this.authentications.BearerAuth.applyToRequest(localVarRequestOptions));
        }
        authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));

        let interceptorPromise = authenticationPromise;
        for (const interceptor of this.interceptors) {
            interceptorPromise = interceptorPromise.then(() => interceptor(localVarRequestOptions));
        }

        return interceptorPromise.then(() => {
            if (Object.keys(localVarFormParams).length) {
                if (localVarUseFormData) {
                    (<any>localVarRequestOptions).formData = localVarFormParams;
                } else {
                    localVarRequestOptions.form = localVarFormParams;
                }
            }
            return new Promise<{ response: http.IncomingMessage; body?: any;  }>((resolve, reject) => {
                localVarRequest(localVarRequestOptions, (error, response, body) => {
                    if (error) {
                        reject(error);
                    } else {
                        if (response.statusCode && response.statusCode >= 200 && response.statusCode <= 299) {
                            resolve({ response: response, body: body });
                        } else {
                            reject(new HttpError(response, body, response.statusCode));
                        }
                    }
                });
            });
        });
    }
}
